
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
  type = "mod"
  name = "loading-bar-mod"
  description = "This mod gets the progress of the Mojang splash screen loading bar in a float."
  version = "0.1.0"
  platform = "fabric"
  license = "MIT"
  source = "https://github.com/Da-Scher/loading-bar-mod"
  author = "Da-Scher <louielouie992@gmail.com>"

# These are global requirements
[requirements]
  minecraft = "~1.18.2"
  fabricLoader = "*"

[dependencies]

[dev]

  [dev.dependencies]
    test-mansion = "*"
